### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [HarleyShort/Teacozy#8]
https://github.com/HarleyShort/Teacozy/blob/master/teacozy%202/style.css#L9-L19

This isn't easily readable or maintainable. Write each individual style on its own line, like so:

```css
selector {
  property: value;
  property: value;
}
```
